version 0.0
os: linux
files:
   - source: /target/DemoTomcatCI.war
   - destination: /tmp/codedeploy/upload
   - source: /scripts/configure_http_port.xsl
   - destination: /tmp/codedeploy/upload

hooks:
   ApplicationStop:
       - location: scripts/stop_application
	 timeout: 300
   ApplicationStart:
       - location: scripts/write_codedeploy_config.sh
       - location: scripts/start_application
         timeout: 300
   ValidateService:
       - location: scripts/basic_health_check.sh
