version: 0.2

phases:
   build:
      commands:
         - mvn install
         
   post_build:
      commands:
         - zip test-deploy.zip appspec.yml target scripts

artifacts:
   files:
      - appspec.yml
      - target/DemoTomcatCI.war
      - scripts/*

cache:
   paths:
      - '/root/.m2/**/*'
