version: 0.2

phases:
   build:
      commands:
         - mvn install
         
   post_build:
      commands:
         - zip -r test-deploy.zip appspec.yml target/DemoTomcatCI.war scripts/*

artifacts:
   files:
      - appspec.yml
      - target/DemoTomcatCI.war
      - scripts/*
      - test-deploy.zip

cache:
   paths:
      - '/root/.m2/**/*'
