version: 0.2

phases:
   build:
      commands:
         - mvn install

artifacts:
   files:
      - appspec.yml
      - target/DemoTomcatCI.war
      - scripts/*
   discard-paths: yes

cache:
   paths:
      - '/root/.m2/**/*'
